server:
  port: 8083

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5435/digibnk_transaction
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8084/realms/digibnk
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

feign:
  client:
    config:
      account-service:
        loggerLevel: BASIC
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    com.digibnk.transaction.client: DEBUG
